registrationUrl=https://app.getcalley.com/registration.aspx
loginUrl=https://app.getcalley.com/Login.aspx

browser=chrome
headless=false
timeoutSeconds=25

userName=Automation Candidate
userEmail=automation.candidate@example.com
userPhone=9876543210
userPassword=Password@12345
companyName=Automation QA Team

agentName=Automation Agent
agentEmail=automation.agent@example.com
agentPhone=9876501234
agentPassword=Agent@12345

listName=Automation Import List
csvPath=src/test/resources/SampleFile.csv
